version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      all-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
      all-security-updates:
        applies-to: security-updates
        patterns:
          - '*'
