name: Setup Node workspace
description: Node.jsをsetupし、repository dependencyをinstallする
inputs:
  node-version:
    description: setupするNode.js version
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --no-audit --no-fund
